all: dos single fork epoll deus_ex_fork

dos: dos.c
	gcc dos.c -o dos

single: single.c
	gcc single.c -o single

fork: fork.c
	gcc fork.c -o fork

epoll: epoll.c
	gcc epoll.c -o epoll

deus_ex_fork: deus_ex_fork.c
	gcc deus_ex_fork.c -o deus_ex_fork

clean:
	rm dos single fork epoll deus_ex_fork

